/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JavaUI;

import java.io.File;
import JavaMainFrame.Assignment2;
import JavaMainFrame.Employee_Details;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author psidh
 */
public class Create_Employee extends javax.swing.JPanel {

    /**
     * Creates new form Create_Employee
     */
    Employee_Details Details;
    public Create_Employee(Employee_Details Details) {
       this.Details = Details;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        First_Name = new javax.swing.JLabel();
        Last_Name = new javax.swing.JLabel();
        Employee_Age = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Start_Date = new javax.swing.JLabel();
        Employee_Level = new javax.swing.JLabel();
        Team_Info = new javax.swing.JLabel();
        Position_Title = new javax.swing.JLabel();
        Mobile_Number = new javax.swing.JLabel();
        Email_ID = new javax.swing.JLabel();
        FirstNameText = new javax.swing.JTextField();
        AgeText = new javax.swing.JTextField();
        LevelText = new javax.swing.JTextField();
        GenderText = new javax.swing.JTextField();
        StartDateText = new javax.swing.JTextField();
        TitleText = new javax.swing.JTextField();
        TeamInfoText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        MobileText = new javax.swing.JTextField();
        Photo = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Employee_ID = new javax.swing.JLabel();
        EmployeeText = new javax.swing.JTextField();
        LastNameText = new javax.swing.JTextField();
        PhotoLable = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Employee Details");

        First_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        First_Name.setText("First Name");

        Last_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Last_Name.setText("Last Name");

        Employee_Age.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employee_Age.setText("Age");

        Gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gender.setText("Gender");

        Start_Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Start_Date.setText("Start Date");

        Employee_Level.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employee_Level.setText("Level");

        Team_Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team_Info.setText("Team Info");
        Team_Info.setMaximumSize(new java.awt.Dimension(27, 16));
        Team_Info.setMinimumSize(new java.awt.Dimension(27, 16));

        Position_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Position_Title.setText("Position Title");

        Mobile_Number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mobile_Number.setText("Mobile Number");

        Email_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email_ID.setText("Email");

        FirstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextActionPerformed(evt);
            }
        });

        AgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTextActionPerformed(evt);
            }
        });

        EmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextActionPerformed(evt);
            }
        });

        Photo.setText("Upload Photo");
        Photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotoActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Employee_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employee_ID.setText("Employee ID");

        EmployeeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeTextActionPerformed(evt);
            }
        });

        PhotoLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Employee_Level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Start_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Employee_Age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(First_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Email_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Mobile_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(Position_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Team_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Employee_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Last_Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GenderText, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                            .addComponent(StartDateText)
                            .addComponent(LevelText)
                            .addComponent(TeamInfoText)
                            .addComponent(TitleText)
                            .addComponent(EmailText)
                            .addComponent(MobileText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AgeText)
                            .addComponent(EmployeeText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FirstNameText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LastNameText))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhotoLable, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(First_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FirstNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                    .addComponent(Last_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Employee_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                    .addComponent(EmployeeText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Employee_Age, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                    .addComponent(AgeText)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PhotoLable, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Gender, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(GenderText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Start_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(StartDateText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(Photo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Employee_Level, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(LevelText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TeamInfoText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Team_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(Position_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mobile_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(Save)
                .addGap(166, 166, 166))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTextActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String First_Name = FirstNameText.getText();
        String Last_Name = LastNameText.getText();
        String Employee_ID = EmployeeText.getText();
        int Age = Integer.parseInt(AgeText.getText());
        String Gender  =    GenderText.getText();
        String Start_Date= StartDateText.getText();
        int Level = Integer.parseInt(LevelText.getText());
        String Team_Info = TeamInfoText.getText();
        String Position_Title= TitleText.getText();
        int Mobile_N0 = Integer.parseInt(MobileText.getText());
        String Email_ID = EmailText.getText();
        File file = new File(jTextField1.getText());
        Assignment2 EmployeeDetails = Details.addEmployee();
        EmployeeDetails.setFirst_Name(First_Name);
        EmployeeDetails.setLast_Name(Last_Name);
        EmployeeDetails.setEmployee_ID(Employee_ID);
        EmployeeDetails.setAge(Age);
        EmployeeDetails.setGender(Gender);
        EmployeeDetails.setStart_Date(Start_Date);
        EmployeeDetails.setLevel(Level);
        EmployeeDetails.setTeam_Info(Team_Info);
        EmployeeDetails.setPosition_Title(Position_Title);
        EmployeeDetails.setMobile_Number(Mobile_N0);
        EmployeeDetails.setEmail_ID(Email_ID);
        EmployeeDetails.setPhoto(file);
        System.out.println();
        JOptionPane.showMessageDialog(this,"Details Have Been Saved Successfully");
        
        FirstNameText.setText("");
        LastNameText.setText("");
        EmployeeText.setText("");
        AgeText.setText("");
        GenderText.setText("");
        StartDateText.setText("");
        LevelText.setText("");
        TeamInfoText.setText("");
        TitleText.setText("");
        MobileText.setText("");
        EmailText.setText("");
        jTextField1.setText("");
        PhotoLable.setIcon(null);
        
        
        
    }//GEN-LAST:event_SaveActionPerformed

    private void PhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotoActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        
        JFileChooser file = new JFileChooser();
        //File file_path = new File(file.getSelectedFile().getAbsolutePath());
        file.showOpenDialog(null);
        File file1= file.getSelectedFile();
       String path = file1.getAbsolutePath();
       jTextField1.setText(path);
         ImageIcon img = new ImageIcon(file1.toString());
         Image imgfit = img.getImage();
         Image imgscale = imgfit.getScaledInstance(146,146,Image.SCALE_SMOOTH);
         PhotoLable.setIcon(new ImageIcon(imgscale));
         JOptionPane.showMessageDialog(this,"Photo Has Been Uploaded Successfully");
    }//GEN-LAST:event_PhotoActionPerformed

    private void EmployeeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeTextActionPerformed

    private void EmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextActionPerformed

    private void FirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeText;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel Email_ID;
    private javax.swing.JTextField EmployeeText;
    private javax.swing.JLabel Employee_Age;
    private javax.swing.JLabel Employee_ID;
    private javax.swing.JLabel Employee_Level;
    private javax.swing.JTextField FirstNameText;
    private javax.swing.JLabel First_Name;
    private javax.swing.JLabel Gender;
    private javax.swing.JTextField GenderText;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JLabel Last_Name;
    private javax.swing.JTextField LevelText;
    private javax.swing.JTextField MobileText;
    private javax.swing.JLabel Mobile_Number;
    private javax.swing.JButton Photo;
    private javax.swing.JLabel PhotoLable;
    private javax.swing.JLabel Position_Title;
    private javax.swing.JButton Save;
    private javax.swing.JTextField StartDateText;
    private javax.swing.JLabel Start_Date;
    private javax.swing.JTextField TeamInfoText;
    private javax.swing.JLabel Team_Info;
    private javax.swing.JTextField TitleText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
