/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JavaUI;

import java.io.File;
import JavaMainFrame.Assignment2;
import JavaMainFrame.Employee_Details;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author psidh
 */
public class Create_Employee extends javax.swing.JPanel {

    /**
     * Creates new form Create_Employee
     */
    Employee_Details jDetails;
    public Create_Employee(Employee_Details jDetails) {
       this.jDetails = jDetails;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFirst_Name = new javax.swing.JLabel();
        jLast_Name = new javax.swing.JLabel();
        jEmployee_Age = new javax.swing.JLabel();
        jGender = new javax.swing.JLabel();
        jStart_Date = new javax.swing.JLabel();
        jEmployee_Level = new javax.swing.JLabel();
        jTeam_Info = new javax.swing.JLabel();
        jPosition_Title = new javax.swing.JLabel();
        jMobile_Number = new javax.swing.JLabel();
        jEmail_ID = new javax.swing.JLabel();
        jFirstNameText = new javax.swing.JTextField();
        jAgeText = new javax.swing.JTextField();
        jLevelText = new javax.swing.JTextField();
        jGenderText = new javax.swing.JTextField();
        jStartDateText = new javax.swing.JTextField();
        jTitleText = new javax.swing.JTextField();
        jTeamInfoText = new javax.swing.JTextField();
        jEmailText = new javax.swing.JTextField();
        jMobileText = new javax.swing.JTextField();
        jPhoto = new javax.swing.JButton();
        jSave = new javax.swing.JButton();
        jEmployee_ID = new javax.swing.JLabel();
        jEmployeeText = new javax.swing.JTextField();
        jLastNameText = new javax.swing.JTextField();
        jPhotoLable = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Employee Details");

        jFirst_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFirst_Name.setText("First Name");

        jLast_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLast_Name.setText("Last Name");

        jEmployee_Age.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmployee_Age.setText("Age");

        jGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jGender.setText("Gender(male.female.other)");

        jStart_Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jStart_Date.setText("Start Date  (dd/mm/yyyy)");

        jEmployee_Level.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmployee_Level.setText("Level");

        jTeam_Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTeam_Info.setText("Team Info");
        jTeam_Info.setMaximumSize(new java.awt.Dimension(27, 16));
        jTeam_Info.setMinimumSize(new java.awt.Dimension(27, 16));

        jPosition_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPosition_Title.setText("Position Title");

        jMobile_Number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMobile_Number.setText("Mobile Number");

        jEmail_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmail_ID.setText("Email");

        jFirstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstNameTextActionPerformed(evt);
            }
        });

        jAgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgeTextActionPerformed(evt);
            }
        });

        jEmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailTextActionPerformed(evt);
            }
        });

        jPhoto.setText("Upload Photo");
        jPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhotoActionPerformed(evt);
            }
        });

        jSave.setText("Save");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jEmployee_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmployee_ID.setText("Employee ID");

        jEmployeeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmployeeTextActionPerformed(evt);
            }
        });

        jPhotoLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPhotoLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jSave, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jEmployee_Level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jStart_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEmployee_Age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFirst_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEmail_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMobile_Number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPosition_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTeam_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEmployee_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLast_Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jGenderText, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                            .addComponent(jStartDateText)
                            .addComponent(jLevelText)
                            .addComponent(jTeamInfoText)
                            .addComponent(jTitleText)
                            .addComponent(jEmailText)
                            .addComponent(jMobileText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jAgeText)
                            .addComponent(jEmployeeText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFirstNameText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLastNameText))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPhotoLable, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFirst_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFirstNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLastNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                    .addComponent(jLast_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jEmployee_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                    .addComponent(jEmployeeText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jEmployee_Age, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                    .addComponent(jAgeText)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPhotoLable, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jGender, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jGenderText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jStart_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jStartDateText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jPhoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEmployee_Level, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLevelText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTeamInfoText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTeam_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jPosition_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMobileText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMobile_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmail_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSave)
                .addGap(166, 166, 166))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jAgeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgeTextActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
        String jFirst_Name = jFirstNameText.getText();
        String jLast_Name = jLastNameText.getText();
        String jEmployee_ID = jEmployeeText.getText();
        int jAge = Integer.parseInt(jAgeText.getText());
        String jGender  =    jGenderText.getText();
        String jStart_Date= jStartDateText.getText();
       
        int jLevel = Integer.parseInt(jLevelText.getText());
        String jTeam_Info = jTeamInfoText.getText();
        String jPosition_Title= jTitleText.getText();
        int jMobile_N0 = Integer.parseInt(jMobileText.getText());
        String jEmail_ID = jEmailText.getText();
        File file = new File(jTextField1.getText());
        
        
//        if((jFirst_Name.equals("")) && (jLast_Name.equals(""))&& (jEmployee_ID.equals("")) && (jAge == 0) && (jGender.equals("")) && (jStart_Date.equals("")) && (jLevel == 0) && (jTeam_Info.equals("")) && (jPosition_Title.equals("")) && (jMobile_N0 == 0) && (jEmail_ID.equals("")) ){
//                JOptionPane.showMessageDialog(this,"Please Enter the Employee Details");
//        }
        if(jFirst_Name.equals("")) {
            JOptionPane.showMessageDialog(this,"Please Enter First Name");
        }
        else if(jLast_Name.equals("")) {
            JOptionPane.showMessageDialog(this,"Please Enter Last Name");
        }
        else if(jEmployee_ID.equals("")) {
            JOptionPane.showMessageDialog(this,"Please Enter Employee ID");
        }
        else if(jAge == 0) {
            JOptionPane.showMessageDialog(this,"Please Enter Age");
        }
      
        else if(!jGender.equalsIgnoreCase("male") && !jGender.equalsIgnoreCase("female") && !jGender.equalsIgnoreCase("other") ) {
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Gender");
        }
        
//        else if(!jGender.toLowerCase().equals("other")) {
//            JOptionPane.showMessageDialog(this,"Please Enter Gender");
//        }
        
        else if(jStart_Date.equals("")) {
            JOptionPane.showMessageDialog(this,"Please Enter Start Date");
        }
        else if(jLevel == 0) {
            JOptionPane.showMessageDialog(this,"Please Enter Level");
        }
        else if(jTeam_Info.equals("")) {
            JOptionPane.showMessageDialog(this,"Please Enter Team Info");
        }
        else if(jPosition_Title.equals("")) {
            JOptionPane.showMessageDialog(this,"Please Enter Position Title");
        }
        else if(jMobile_N0 == 0) {
            JOptionPane.showMessageDialog(this,"Please Enter First Name");
        }
        else if(jEmail_ID.equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter Email ID");
        }
        else if (jPhotoLable.getIcon()==null){
            JOptionPane.showMessageDialog(this,"Please upload an Image");
        }
        else if (!jStart_Date.matches("^[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2}$")){
            JOptionPane.showMessageDialog(this,"Please Enter a valid Date");
        }
        else if(!jEmail_ID.matches("^(.+)@(.+)$")){
            JOptionPane.showMessageDialog(this,"Please Enter a valid Email ID");
        }
        else 
            
        {
        Assignment2 EmployeeDetails = jDetails.addjEmployee();
        EmployeeDetails.setjFirst_Name(jFirst_Name);
        EmployeeDetails.setjLast_Name(jLast_Name);
        EmployeeDetails.setjEmployee_ID(jEmployee_ID);
        EmployeeDetails.setjAge(jAge);
        EmployeeDetails.setjGender(jGender);
        EmployeeDetails.setjStart_Date(jStart_Date);
        EmployeeDetails.setjLevel(jLevel);
        EmployeeDetails.setjTeam_Info(jTeam_Info);
        EmployeeDetails.setjPosition_Title(jPosition_Title);
        EmployeeDetails.setjMobile_Number(jMobile_N0);
        EmployeeDetails.setjEmail_ID(jEmail_ID);
        EmployeeDetails.setjPhoto(file);
        System.out.println();
        JOptionPane.showMessageDialog(this,"Details Have Been Saved Successfully");
        
        jFirstNameText.setText("");
        jLastNameText.setText("");
        jEmployeeText.setText("");
        jAgeText.setText("");
        jGenderText.setText("");
        jStartDateText.setText("");
        jLevelText.setText("");
        jTeamInfoText.setText("");
        jTitleText.setText("");
        jMobileText.setText("");
        jEmailText.setText("");
        jTextField1.setText("");
        jPhotoLable.setIcon(null);
        
        } 
        
    }//GEN-LAST:event_jSaveActionPerformed

    private void jPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhotoActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        
        JFileChooser file = new JFileChooser();
        //File file_path = new File(file.getSelectedFile().getAbsolutePath());
        file.showOpenDialog(null);
        File file1= file.getSelectedFile();
       String path = file1.getAbsolutePath();
       jTextField1.setText(path);
         ImageIcon img = new ImageIcon(file1.toString());
         Image imgfit = img.getImage();
         Image imgscale = imgfit.getScaledInstance(146,146,Image.SCALE_SMOOTH);
         jPhotoLable.setIcon(new ImageIcon(imgscale));
         JOptionPane.showMessageDialog(this,"Photo Has Been Uploaded Successfully");
         
         if( jPhoto == null){
        JOptionPane.showMessageDialog(this,"Please Upload Photo");

    }
    }//GEN-LAST:event_jPhotoActionPerformed

    private void jEmployeeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmployeeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmployeeTextActionPerformed

    private void jEmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailTextActionPerformed

    private void jFirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstNameTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAgeText;
    private javax.swing.JTextField jEmailText;
    private javax.swing.JLabel jEmail_ID;
    private javax.swing.JTextField jEmployeeText;
    private javax.swing.JLabel jEmployee_Age;
    private javax.swing.JLabel jEmployee_ID;
    private javax.swing.JLabel jEmployee_Level;
    private javax.swing.JTextField jFirstNameText;
    private javax.swing.JLabel jFirst_Name;
    private javax.swing.JLabel jGender;
    private javax.swing.JTextField jGenderText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jLastNameText;
    private javax.swing.JLabel jLast_Name;
    private javax.swing.JTextField jLevelText;
    private javax.swing.JTextField jMobileText;
    private javax.swing.JLabel jMobile_Number;
    private javax.swing.JButton jPhoto;
    private javax.swing.JLabel jPhotoLable;
    private javax.swing.JLabel jPosition_Title;
    private javax.swing.JButton jSave;
    private javax.swing.JTextField jStartDateText;
    private javax.swing.JLabel jStart_Date;
    private javax.swing.JTextField jTeamInfoText;
    private javax.swing.JLabel jTeam_Info;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTitleText;
    // End of variables declaration//GEN-END:variables
}
