/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaUI;

import JavaMainFrame.Assignment2;
import JavaMainFrame.Employee_Details;



/**
 *
 * @author psidh
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    Employee_Details Details;
    public Employee() {
        Details = new Employee_Details();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPane = new javax.swing.JSplitPane();
        ControlAreaPanel = new javax.swing.JPanel();
        Create_Employee = new javax.swing.JButton();
        View_Employee = new javax.swing.JButton();
        WorkAreaPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Create_Employee.setText("Create");
        Create_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_EmployeeActionPerformed(evt);
            }
        });

        View_Employee.setText("View");
        View_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_EmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlAreaPanelLayout = new javax.swing.GroupLayout(ControlAreaPanel);
        ControlAreaPanel.setLayout(ControlAreaPanelLayout);
        ControlAreaPanelLayout.setHorizontalGroup(
            ControlAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Create_Employee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(View_Employee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ControlAreaPanelLayout.setVerticalGroup(
            ControlAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlAreaPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(Create_Employee)
                .addGap(35, 35, 35)
                .addComponent(View_Employee)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        MainPane.setLeftComponent(ControlAreaPanel);
        MainPane.setRightComponent(WorkAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Create_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_EmployeeActionPerformed
        // TODO add your handling code here:
         Create_Employee Detail = new Create_Employee(Details);
        MainPane.setRightComponent(Detail);
    }//GEN-LAST:event_Create_EmployeeActionPerformed

    private void View_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_EmployeeActionPerformed
        // TODO add your handling code here:
        View_Employee View = new View_Employee(Details);
        MainPane.setRightComponent(View);
    }//GEN-LAST:event_View_EmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlAreaPanel;
    private javax.swing.JButton Create_Employee;
    private javax.swing.JSplitPane MainPane;
    private javax.swing.JButton View_Employee;
    private javax.swing.JScrollPane WorkAreaPanel;
    // End of variables declaration//GEN-END:variables
}
