/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaUI;

import JavaMainFrame.Assignment2;
import JavaMainFrame.Employee_Details;



/**
 *
 * @author psidh
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    Employee_Details jDetails;
    public Employee() {
        jDetails = new Employee_Details();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPane = new javax.swing.JSplitPane();
        jControlAreaPanel = new javax.swing.JPanel();
        jCreate_Employee = new javax.swing.JButton();
        jView_Employee = new javax.swing.JButton();
        jWorkAreaPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCreate_Employee.setText("Create");
        jCreate_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreate_EmployeeActionPerformed(evt);
            }
        });

        jView_Employee.setText("View");
        jView_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jView_EmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jControlAreaPanelLayout = new javax.swing.GroupLayout(jControlAreaPanel);
        jControlAreaPanel.setLayout(jControlAreaPanelLayout);
        jControlAreaPanelLayout.setHorizontalGroup(
            jControlAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCreate_Employee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jView_Employee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jControlAreaPanelLayout.setVerticalGroup(
            jControlAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jControlAreaPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jCreate_Employee)
                .addGap(35, 35, 35)
                .addComponent(jView_Employee)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jMainPane.setLeftComponent(jControlAreaPanel);
        jMainPane.setRightComponent(jWorkAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jMainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCreate_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreate_EmployeeActionPerformed
        // TODO add your handling code here:
         Create_Employee jDetail = new Create_Employee(jDetails);
        jMainPane.setRightComponent(jDetail);
    }//GEN-LAST:event_jCreate_EmployeeActionPerformed

    private void jView_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jView_EmployeeActionPerformed
        // TODO add your handling code here:
        View_Employee jView = new View_Employee(jDetails);
        jMainPane.setRightComponent(jView);
    }//GEN-LAST:event_jView_EmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jControlAreaPanel;
    private javax.swing.JButton jCreate_Employee;
    private javax.swing.JSplitPane jMainPane;
    private javax.swing.JButton jView_Employee;
    private javax.swing.JScrollPane jWorkAreaPanel;
    // End of variables declaration//GEN-END:variables
}
