/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JavaUI;
import JavaMainFrame.Assignment2;
import JavaMainFrame.Employee_Details;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author psidh
 */
public class View_Employee extends javax.swing.JPanel {

    /**
     * Creates new form View_Employee
     */
    Employee_Details jDetails;
    public View_Employee(Employee_Details jDetails) {
       this.jDetails = jDetails;
        initComponents();
        
        fillemployeedetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEmployee_table = new javax.swing.JTable();
        jView = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jEmployee_ID = new javax.swing.JLabel();
        jEmployeeText = new javax.swing.JTextField();
        jLastNameText = new javax.swing.JTextField();
        jMobile_Number = new javax.swing.JLabel();
        jFirstNameText = new javax.swing.JTextField();
        jAgeText = new javax.swing.JTextField();
        jLevelText = new javax.swing.JTextField();
        jGenderText = new javax.swing.JTextField();
        jStartDateText = new javax.swing.JTextField();
        jTitleText = new javax.swing.JTextField();
        jTeamInfoText = new javax.swing.JTextField();
        jEmailText = new javax.swing.JTextField();
        jFirst_Name = new javax.swing.JLabel();
        jMobileText = new javax.swing.JTextField();
        jLast_Name = new javax.swing.JLabel();
        jEmployee_Age = new javax.swing.JLabel();
        jGender = new javax.swing.JLabel();
        jStart_Date = new javax.swing.JLabel();
        jEmployee_Level = new javax.swing.JLabel();
        jTeam_Info = new javax.swing.JLabel();
        jPosition_Title = new javax.swing.JLabel();
        jEmail_ID = new javax.swing.JLabel();
        jPhoto = new javax.swing.JButton();
        jUpdate = new javax.swing.JButton();
        jSearch = new javax.swing.JButton();
        jSearchText = new javax.swing.JTextField();
        jClearSearch = new javax.swing.JButton();
        jPhotoLable = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Employee Details");

        jEmployee_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Mobile No.", "Email ID", "Path"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jEmployee_table);

        jView.setText("View");
        jView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewActionPerformed(evt);
            }
        });

        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jEmployee_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmployee_ID.setText("Employee ID");

        jEmployeeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmployeeTextActionPerformed(evt);
            }
        });

        jLastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastNameTextActionPerformed(evt);
            }
        });

        jMobile_Number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMobile_Number.setText("Mobile Number");

        jAgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgeTextActionPerformed(evt);
            }
        });

        jEmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailTextActionPerformed(evt);
            }
        });

        jFirst_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFirst_Name.setText("First Name");

        jLast_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLast_Name.setText("Last Name");

        jEmployee_Age.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmployee_Age.setText("Age");

        jGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jGender.setText("Gender");

        jStart_Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jStart_Date.setText("Start Date");

        jEmployee_Level.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmployee_Level.setText("Level");

        jTeam_Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTeam_Info.setText("Team Info");
        jTeam_Info.setMaximumSize(new java.awt.Dimension(27, 16));
        jTeam_Info.setMinimumSize(new java.awt.Dimension(27, 16));

        jPosition_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPosition_Title.setText("Position Title");

        jEmail_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmail_ID.setText("Email");

        jPhoto.setText("Update Photo");
        jPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhotoActionPerformed(evt);
            }
        });

        jUpdate.setText("Update");
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });

        jSearch.setText("Search");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        jClearSearch.setText("Clear");
        jClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearSearchActionPerformed(evt);
            }
        });

        jPhotoLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPhotoLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1266, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jEmployee_Level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jStart_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEmployee_Age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFirst_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMobile_Number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPosition_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTeam_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEmployee_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLast_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jEmail_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jGenderText)
                            .addComponent(jStartDateText)
                            .addComponent(jLevelText)
                            .addComponent(jTeamInfoText)
                            .addComponent(jTitleText)
                            .addComponent(jEmailText)
                            .addComponent(jMobileText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jAgeText)
                            .addComponent(jEmployeeText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLastNameText)
                            .addComponent(jFirstNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPhotoLable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPhoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jView, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jClearSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jView)
                    .addComponent(jDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFirstNameText)
                        .addComponent(jSearchText)
                        .addComponent(jSearch)
                        .addComponent(jClearSearch))
                    .addComponent(jFirst_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLast_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jEmployeeText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmployee_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jEmployee_Age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jGenderText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jStart_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jStartDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jEmployee_Level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPhotoLable, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTeam_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTeamInfoText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTitleText)
                    .addComponent(jPosition_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMobile_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMobileText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEmail_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEmailText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jUpdate)
                .addGap(206, 206, 206))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewActionPerformed
        // TODO add your handling code here:
        int SelectedRow = jEmployee_table.getSelectedRow();
         if (SelectedRow<0){
                 JOptionPane.showMessageDialog(this,"Please Select a Row to View");
                 return;
         }
        DefaultTableModel model = (DefaultTableModel) jEmployee_table.getModel();
        Assignment2 Selected_Row = (Assignment2)model.getValueAt(SelectedRow,0);
        jFirstNameText.setText(Selected_Row.getjFirst_Name());
        jLastNameText.setText(Selected_Row.getjLast_Name());
        jEmployeeText.setText(Selected_Row.getjEmployee_ID());
        jAgeText.setText(String.valueOf(Selected_Row.getjAge()));
        jGenderText.setText(Selected_Row.getjGender());
        jStartDateText.setText(Selected_Row.getjStart_Date());
        jLevelText.setText(String.valueOf(Selected_Row.getjLevel()));
        jTeamInfoText.setText(Selected_Row.getjTeam_Info());
        jTitleText.setText(Selected_Row.getjPosition_Title());
        jMobileText.setText(String.valueOf(Selected_Row.getjMobile_Number()));
        jEmailText.setText(Selected_Row.getjEmail_ID());
        jTextField1.setText(String.valueOf(Selected_Row.getjPhoto()));
         ImageIcon img = new ImageIcon(Selected_Row.getjPhoto().toString());
         Image imgfit = img.getImage();
         Image imgscale = imgfit.getScaledInstance(146,146, Image.SCALE_SMOOTH);
         jPhotoLable.setIcon(new ImageIcon(imgscale));
        
    }//GEN-LAST:event_jViewActionPerformed

    private void jEmployeeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmployeeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmployeeTextActionPerformed

    private void jLastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLastNameTextActionPerformed

    private void jAgeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgeTextActionPerformed

    private void jEmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailTextActionPerformed

    private void jPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhotoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        JFileChooser file = new JFileChooser();
//        File file_path = new File(file.getSelectedFile().getAbsolutePath());
        file.showOpenDialog(null);
        File file1= file.getSelectedFile();
        String path = file1.getAbsolutePath();
        jTextField1.setText(path);
         ImageIcon img = new ImageIcon(file1.toString());
         Image imgfit = img.getImage();
         Image imgscale = imgfit.getScaledInstance(146,146,Image.SCALE_SMOOTH);
         jPhotoLable.setIcon(new ImageIcon(imgscale));
         JOptionPane.showMessageDialog(this,"Photo Has Been Updated Successfully");
    }//GEN-LAST:event_jPhotoActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        // TODO add your handling code here:
        int SelectedRow = jEmployee_table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jEmployee_table.getModel();
        Assignment2 Selected_Row = (Assignment2)model.getValueAt(SelectedRow,0);
       
         if (SelectedRow >= 0){
             model.setValueAt(jFirstNameText.getText(),SelectedRow,0);   
             model.setValueAt(jLastNameText.getText(),SelectedRow,1);
             model.setValueAt(jEmployeeText.getText(),SelectedRow,2);
             model.setValueAt(jAgeText.getText(),SelectedRow,3);
             model.setValueAt(jGenderText.getText(),SelectedRow,4);
             model.setValueAt(jStartDateText.getText(),SelectedRow,5);
             model.setValueAt(jLevelText.getText(),SelectedRow,6);
             model.setValueAt(jTeamInfoText.getText(),SelectedRow,7);
             model.setValueAt(jTitleText.getText(),SelectedRow,8);
             model.setValueAt(jMobileText.getText(),SelectedRow,9);
             model.setValueAt(jEmailText.getText(),SelectedRow,10);
             model.setValueAt(jTextField1.getText(),SelectedRow,11);
             ImageIcon img = new ImageIcon(Selected_Row.getjPhoto().toString());
         Image imgfit = img.getImage();
         Image imgscale = imgfit.getScaledInstance(146,146, Image.SCALE_SMOOTH);
         jPhotoLable.setIcon(new ImageIcon(imgscale));
             JOptionPane.showMessageDialog(this,"Updated Successfully");
        Selected_Row.setjFirst_Name(jFirstNameText.getText());
        Selected_Row.setjLast_Name(jLastNameText.getText());
        Selected_Row.setjEmployee_ID(jEmployeeText.getText());
        Selected_Row.setjAge(Integer.parseInt(jAgeText.getText()));
        Selected_Row.setjGender(jGenderText.getText());
        Selected_Row.setjStart_Date(jStartDateText.getText());
        Selected_Row.setjLevel(Integer.parseInt(jLevelText.getText()));
        Selected_Row.setjTeam_Info(jTeamInfoText.getText());
        Selected_Row.setjPosition_Title(jTitleText.getText());
        Selected_Row.setjMobile_Number(Integer.parseInt(jMobileText.getText()));
        Selected_Row.setjEmail_ID(jEmailText.getText());
       Selected_Row.setjPhoto(new File(jTextField1.getText()));
        
        jFirstNameText.setText("");
        jLastNameText.setText("");
        jEmployeeText.setText("");
        jAgeText.setText("");
        jGenderText.setText("");
        jStartDateText.setText("");
        jLevelText.setText("");
        jTeamInfoText.setText("");
        jTitleText.setText("");
        jMobileText.setText("");
        jEmailText.setText("");
        jPhotoLable.setIcon(null);
        jTextField1.setText("");
        fillemployeedetails();
         }else{
         JOptionPane.showMessageDialog(this,"Error, No update");
         jFirstNameText.setText("");
        jLastNameText.setText("");
        jEmployeeText.setText("");
        jAgeText.setText("");
        jGenderText.setText("");
        jStartDateText.setText("");
        jLevelText.setText("");
        jTeamInfoText.setText("");
        jTitleText.setText("");
        jMobileText.setText("");
        jEmailText.setText("");
        jPhotoLable.setIcon(null);
        fillemployeedetails();
         }
        
    }//GEN-LAST:event_jUpdateActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        
        int SelectedRow = jEmployee_table.getSelectedRow();
         if (SelectedRow<0){
                 JOptionPane.showMessageDialog(this,"Please Select a Row to Delete");
                 return;
         }
        DefaultTableModel model = (DefaultTableModel) jEmployee_table.getModel();
        Assignment2 Selected_Row = (Assignment2)model.getValueAt(SelectedRow,0);
        jDetails.Delete_Employee(Selected_Row);
        JOptionPane.showMessageDialog(this,"Employee Details Deleted Successfully");
        jFirstNameText.setText("");
        jLastNameText.setText("");
        jEmployeeText.setText("");
        jAgeText.setText("");
        jGenderText.setText("");
        jStartDateText.setText("");
        jLevelText.setText("");
        jTeamInfoText.setText("");
        jTitleText.setText("");
        jMobileText.setText("");
        jEmailText.setText("");
        jPhotoLable.setIcon(null);
        jTextField1.setText("");
        fillemployeedetails();
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // TODO add your handling code here:
         String jEmployeeDetails = jSearchText.getText().toLowerCase();
         Search(jEmployeeDetails);
    }//GEN-LAST:event_jSearchActionPerformed

    private void jClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearSearchActionPerformed
        // TODO add your handling code here:
        jSearchText.setText(null);
        String jEmployeeDetails = jSearchText.getText().toLowerCase();
        Search(jEmployeeDetails);
    }//GEN-LAST:event_jClearSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAgeText;
    private javax.swing.JButton jClearSearch;
    private javax.swing.JButton jDelete;
    private javax.swing.JTextField jEmailText;
    private javax.swing.JLabel jEmail_ID;
    private javax.swing.JTextField jEmployeeText;
    private javax.swing.JLabel jEmployee_Age;
    private javax.swing.JLabel jEmployee_ID;
    private javax.swing.JLabel jEmployee_Level;
    private javax.swing.JTable jEmployee_table;
    private javax.swing.JTextField jFirstNameText;
    private javax.swing.JLabel jFirst_Name;
    private javax.swing.JLabel jGender;
    private javax.swing.JTextField jGenderText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jLastNameText;
    private javax.swing.JLabel jLast_Name;
    private javax.swing.JTextField jLevelText;
    private javax.swing.JTextField jMobileText;
    private javax.swing.JLabel jMobile_Number;
    private javax.swing.JButton jPhoto;
    private javax.swing.JLabel jPhotoLable;
    private javax.swing.JLabel jPosition_Title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearch;
    private javax.swing.JTextField jSearchText;
    private javax.swing.JTextField jStartDateText;
    private javax.swing.JLabel jStart_Date;
    private javax.swing.JTextField jTeamInfoText;
    private javax.swing.JLabel jTeam_Info;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTitleText;
    private javax.swing.JButton jUpdate;
    private javax.swing.JButton jView;
    // End of variables declaration//GEN-END:variables

    private void fillemployeedetails() {
         DefaultTableModel Table = (DefaultTableModel) jEmployee_table.getModel();
         Table.setRowCount(0);
         
         for (Assignment2 jEmployee : jDetails.getjDetails()){
            Object[] row = new Object[12];
            row[0] = jEmployee;
            row[1] = jEmployee.getjLast_Name();
            row[2] = jEmployee.getjEmployee_ID();
            row[3] = jEmployee.getjAge();
            row[4] = jEmployee.getjGender();
            row[5] = jEmployee.getjStart_Date();
            row[6] = jEmployee.getjLevel();
            row[7] = jEmployee.getjTeam_Info();
            row[8] = jEmployee.getjPosition_Title();
            row[9] = jEmployee.getjMobile_Number();
            row[10] = jEmployee.getjEmail_ID();
            row[11] = jEmployee.getjPhoto();
            Table.addRow(row);
         }
    }

    private void Search(String EmployeeDetails) {
              DefaultTableModel jTable = (DefaultTableModel) jEmployee_table.getModel();
              TableRowSorter<DefaultTableModel> jEmployeeSearch = new TableRowSorter<DefaultTableModel>(jTable);
              jEmployee_table.setRowSorter(jEmployeeSearch);
              jEmployeeSearch.setRowFilter(RowFilter.regexFilter(EmployeeDetails));
              
    }
}
